//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baitap.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Xml.Linq;

    public partial class Brand
    {
        [Display(Name = "Số ID  ")]
        [Required(ErrorMessage = "ID sản phẩm không được để trống")]
        public int id { get; set; }
        [Display(Name = "Tên sản phẩm")]
        public string Name { get; set; }
        [Display(Name = "Hình ảnh")]
        public string Avatar { get; set; }
        [Display(Name = "Thể loại ID sản phẩm ")]
        public string Slug { get; set; }
        [Display(Name = "Loại")]
        public Nullable<bool> ShowOnlHomePage { get; set; }
        [Display(Name = "Ngày cập nhật")]
        public Nullable<int> DisphayOrder { get; set; }
        [Display(Name = "Ngày tạo")]

        public Nullable<System.DateTime> CreatedOnUtc { get; set; }

        public Nullable<System.DateTime> UpdatedOnUtc { get; set; }

        public Nullable<bool> Delected { get; set; }

        [NotMapped]
        public System.Web.HttpPostedFileBase ImageUpLoad { get; set; }
    }
}
